version: '3'

services:
    app:
        build: .
        container_name: app
        restart: always
        volumes:
            - .:/usr/src/app
        ports:
            - '8889:3000'
        command: yarn run dev
        depends_on:
          - mongo
    mongo:
        container_name: mongo
        restart: always
        image: mongo
        volumes:
            - /data/debug-hospedaup:/data/db
        expose:
          - '27017'
